#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "soapbox"
name = "Soapbox"
description.en = "Alternative frontend for Pleroma"
description.fr = "Interface alternative pour Pleroma"

version = "v3.2.0~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://soapbox.pub/"
admindoc = "https://docs.soapbox.pub/"
code = "https://gitlab.com/soapbox-pub/soapbox-fe"
cpe = "cpe:2.3:a:soapbox_project:soapbox"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.backend]
    ask.en = "The root domain of Pleroma instance installed"
    ask.fr = "Le domaine racine de l'instance pleroma installée"
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://gitlab.com/soapbox-pub/soapbox-fe/-/archive/v3.2.0/soapbox-fe-v3.2.0.tar.bz2"
    sha256 = "f7640a4fb6bef5ee89eb8d7af5ce10b0b149dd6afc0ac6b284738f1629afc39a"
    format = "zip"
    autoupdate.strategy = "latest_gitlab_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
